### ISSUE TITLE
Documentation on requirements

### ISSUE THREAD

**Issue by ioana-blue** [CoderPat/structured-neural-summarization#2]
It would be nice if the readme included a couple of lines on requirements, specially the tensorflow version that this code was ran with (I'm getting an error which I'm guessing it's due to API TF breakage).

**Comment by CoderPat** [comment]
I guess this issue is no longer relevant given #3 ? The requirements should be mostly solved by installing OpenGNN library.

**Comment by bzz** [comment]
Sorry for butting in and think you for maintaining and improving the code! 
I was wondering, is there is a reason not to include a `requirement.txt`?

**Comment by CoderPat** [comment]
It could be done, but the package depends on
https://github.com/CoderPat/OpenGNN which isn't uploaded in pip, and since
installing it would already install all the dependencies, I just though it
would be redundant.
However the addiction of the nltk dependecie might make it worth it to
include it, will look into it.

**Comment by ioana-blue** [comment]
`rouge` is also required.
